# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demystify < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/khulnasoft-lab/demystify/"
  version "0.12.0-SNAPSHOT-ead2899"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft-lab/demystify/releases/download/v0.12.0/demystify_0.12.0-SNAPSHOT-ead2899_darwin_amd64.tar.gz"
      sha256 "2519c7c5d3a9582f4e0edb7995156097afed007aa53b97587cdf9792cfed134e"

      def install
        bin.install "demystify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khulnasoft-lab/demystify/releases/download/v0.12.0/demystify_0.12.0-SNAPSHOT-ead2899_darwin_arm64.tar.gz"
      sha256 "d939404dafa2cd8b12a3fd9d082be3ed3040d15b1cf522abc93fb01433b0db61"

      def install
        bin.install "demystify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khulnasoft-lab/demystify/releases/download/v0.12.0/demystify_0.12.0-SNAPSHOT-ead2899_linux_arm64.tar.gz"
      sha256 "3a77bc1bd6ac2e2eacb3bc6e6b089267794e6261e1deeb1745bbd0e5932a0516"

      def install
        bin.install "demystify"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft-lab/demystify/releases/download/v0.12.0/demystify_0.12.0-SNAPSHOT-ead2899_linux_amd64.tar.gz"
      sha256 "32b0cbd563637ada077cd06ef2a3d46a02503613e341ca1e678289f5bcd73e4e"

      def install
        bin.install "demystify"
      end
    end
  end
end
